<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EverybodyCodes.Solutions\EverybodyCodes.Solutions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\resources\**\*.*" CopyToOutputDirectory="PreserveNewest" LinkBase="resources" />
    <None Update="..\..\resources\y2024\quest01\part3.txt">
      <Link>resources\y2024\quest01\part3.txt</Link>
    </None>
  </ItemGroup>

</Project>
